(deftheme jlatt "jlatt's theme")

(custom-theme-set-faces 
 'jlatt
 '(default ((t (:background "black" :foreground "#eee"))))
 '(modeline ((t (:background "white" :foreground "dodgerblue"))))
 '(bold ((t (:underline t :background "black" :foreground "white"))))
 '(bold-italic ((t (:underline t :foreground "white"))))
 '(calendar-today-face ((t (:underline t))))
 '(diary-face ((t (:foreground "red"))))
 '(font-lock-builtin-face ((t (:foreground "dodgerblue"))))
 '(font-lock-comment-face ((t (:foreground "cyan"))))
 '(font-lock-constant-face ((t (:foreground "VioletRed1"))))
 '(font-lock-function-name-face ((t (:foreground "cyan"))))
 '(font-lock-keyword-face ((t (:foreground "DarkOrange1"))))
 '(font-lock-string-face ((t (:foreground "red"))))
 '(font-lock-type-face ((t (:foreground "lime green"))))
 '(font-lock-variable-name-face ((t (:foreground "dodgerblue"))))
 '(font-lock-warning-face ((t (:bold t :foreground "magenta"))))
 '(highlight ((t (:background "blue" :foreground "lime green"))))
 '(holiday-face ((t (:background "cyan"))))
 '(info-menu-5 ((t (:underline t))))
 '(info-node ((t (:italic t :bold t))))
 '(info-xref ((t (:bold t))))
 '(italic ((t (:italic: t))))
 '(modeline-buffer-id ((t (:background "white" :foreground "red"))))
 '(modeline-mousable ((t (:background "white" :foreground "magenta"))))
 '(modeline-mousable-minor-mode ((t (:background "white" :foreground "yellow"))))
 '(region ((t (:background "white" :foreground "black"))))
 '(zmacs-region ((t (:background "cyan" :foreground "black"))))
 '(secondary-selection ((t (:background "blue"))))
 '(show-paren-match-face ((t (:background "aqua"))))
 '(show-paren-mismatch-face ((t (:background "magenta" :foreground "white"))))
 '(underline ((t (:underline t))))
 )
;; ((background-color . "black")
;;  (background-mode . dark)
;;  (border-color . "blue")
;;  (cursor-color . "gray30")
;;   (foreground-color . "white")
;;   (mouse-color . "black"))
;;  (default ((t (nil))))
;;  (message-cited-text-face ((t (:foreground "red"))))
;;  (message-header-cc-face ((t (:bold t :foreground "yellow"))))
;;  (message-header-name-face ((t (:foreground "yellow"))))
;;  (message-header-newsgroups-face ((t (:italic t :bold t :foreground "lime green"))))
;;  (message-header-other-face ((t (:foreground "#b00000"))))
;;  (message-header-subject-face ((t (:foreground "yellow"))))
;;  (message-header-to-face ((t (:bold t :foreground "yellow"))))
;;  (message-header-xheader-face ((t (:foreground "dodgerblue"))))
;;  (message-mml-face ((t (:foreground "yellow"))))
;;  (message-separator-face ((t (:foreground "dodgerblue"))))
